#!/bin/bash

#SBATCH -N 1                      # number of nodes
#SBATCH -n 4                      # number of cores
#SBATCH -t 0-00:45 # Runtime in D-HH:MM.   #typically it takes about 30 min to build and submit 
#SBATCH -p huce_intel # Partition to submit to
#SBATCH --mem=5000 # Memory pool for all cores (see also --mem-per-cpu)
#SBATCH -o hostname_%j.out # File to which STDOUT will be written
#SBATCH -e hostname_%j.err # File to which STDERR will be written
#SBATCH --mail-type=END
#SBATCH --mail-user=            # ADD YOUR EMAIL HERE 

> ~/buildout
./build_cesm_bash.sh >> ~/buildout

